### PR TITLE
Force trailing slash path redirect

### PR DESCRIPTION
**Pull request by adesege**
As per [this comment](https://github.com/cloudflare/cloudflare-docs/pull/2599#issuecomment-976905564), this PR 

1. removes `gatsby-plugin-remove-trailing-slashes` package so that browser urls and canonical urls will have trailing slash append to them.
2. Fixes https://github.com/cloudflare/cloudflare-docs-engine/pull/365#issuecomment-980085538 by removing `gatsby-plugin-canonical-urls` package and implementing the plugin locally.

This PR is blocking https://github.com/cloudflare/cloudflare-docs/pull/2709 and https://github.com/cloudflare/cloudflare-docs/pull/2599

# How?

1. cd into `developers.cloudflare.com` in cloudflare-docs.
1. Install dependencies and run the project using `npm run start`.
1. Visit your browser and you should see a link rel="canonical" tag in the devtools source code.
1. To test other products, clone this PR https://github.com/cloudflare/cloudflare-docs-engine/pull/370 into cloudflare-docs-engine
1. Point `cloudflare-docs-engine` dependency in `products/images/package.json` to the local version of https://github.com/cloudflare/cloudflare-docs-engine/pull/370.
1. Run `npm install` then `npm run bootstrap`.
1. Run `npm run develop` to build and start the application.
1. Visit http://localhost:8000/cloudflare-images/resize-images/ and check the source code for the appropriate link rel="canonical" tag.
1. Repeat `steps 5-8`. For step 8, remember to change the url to point to the appropriate product you are testing for.

### CODE REVIEW

**Comment by lukeed** [comment]
Hey, thank you for this, but this is actually a pretty significant breaking change. And from `cloudflare-docs` perspective, I don't think it should be merged. The #365 PR should have been more heavily analyzed too – thankfully it didn't actually do anything because of the version mismatch.

The reasons for this is that it adjusts the canonical URLs for all documents. Of course, that's the point of these PRs, but that's a big deal from a SEO perspective. For example, all of the docs already use non-trailing canonicals: 

```html
<link rel="canonical" href="https://developers.cloudflare.com/platform/environment-variables" data-baseprotocol="https:" data-basehost="developers.cloudflare.com"/>
```

> [View Source](https://developers.cloudflare.com/workers/platform/environment-variables)

Even though the proper 301 redirecting is in place, changing all the docs pages (or even any amount of them accidentally) is potentially problematic & will/can cause search engines to drop existing value to the previous document locations.

**Comment by adesege** [comment]
Hi @lukeed,

Thanks for the feedback.

We had an extensive discussion on whether we should use paths with trailing slash as canonical urls or not in https://github.com/cloudflare/cloudflare-docs/pull/2599 and [this ticket](https://jira.cfops.it/browse/MRK-13498).

cc: @kodster28

**Comment by adesege** [comment]
@kodster28 Do you have thoughts on @lukeed's comment?

**Comment by kodster28** [comment]
Howdy @adesege, I'll add more context on the ticket itself, but given the back and forth and some underlying complications, I think it's better to close out this PR and not move forward with canonical tags.

**Comment by kodster28** [comment]
Also, thanks @lukeed for the additional context. TiL SEO is a lot more complicated that I realized.

**Pull request closed without merging**
