### PR TITLE
Add a GitHub action to lint the Markdown.

### PR DESCRIPTION
**Pull request by jbampton**
Add a basic Markdownlint config file.
Lint some Markdown.

### CODE REVIEW

**Comment by adamschwartz** [comment]
@jbampton Thanks so much for these.

I think this could really help improve the docs quality/consistency.

I had a few questions to help me understand how this works:

- I didn’t see a change to `package.json`. Should we make `markdownlint-cli` a devDependency?
- As for the Github action, I take it this will show a success/fail check on PRs. Please confirm if this is the case. Also, will a fail on this action prevent the deploy action? Is that what we want?

cc @ispivey @signalnerve @rita3ko for their thoughts.

**Comment by jbampton** [comment]
I think it is up to you if we add `markdownlint-cli` as a devDependency.  I have added this feature to some other repos and we did not add it as a dependency.

Yes this shows up as successful or as failed.  You can see it passed for this PR.  It will print out the line numbers of the failures including what failed if it does fail.

This check is separate to the deploy action so a failure on the markdown lint will not prevent the deploy action from working but we could change this if needed.

**Comment by signalnerve** [comment]
+1 on this being on PRs only, i don't think it should block deploys

is there a skip rule? if we're managing an internal PR, we don't want to be blocked by linting if we really need to merge something. also don't want those potential issues to get bunched up w/ any potential new linting issues found in external PRs. 

thanks, this is super cool btw

**Comment by jbampton** [comment]
This check is separate to the deploy.  So it won't block the deploy action. And it won't block existing PRs just merge them and fixing the linting errors another time.  It will still deploy.

I have it setup as seen in the image below so we can still deploy even if the linting fails in this repo ->  
https://github.com/slurpcode/slurp 

This is depoying -> https://magic.slurp.workers.dev/  👍 

Screen Shot 2020-09-22 at 8 10 30 pm

Also there are rules and you can even run `--fix` for auto fixing simple errors.

```
markdownlint --help
 
  Usage: markdownlint [options] <files|directories|globs>
 
  MarkdownLint Command Line Interface
 
  Options:
 
    -h, --help                                  output usage information
    -V, --version                               output the version number
    -f, --fix                                   fix basic errors (does not work with STDIN)
    -s, --stdin                                 read from STDIN (does not work with files)
    -o, --output [outputFile]                   write issues to file (no console)
    -c, --config [configFile]                   configuration file (JSON, JSONC, JS, or YAML)
    -i, --ignore [file|directory|glob]          file(s) to ignore/exclude
    -p, --ignore-path [file]                    path to file with ignore pattern(s)
    -r, --rules  [file|directory|glob|package]  custom rule files
```

https://www.npmjs.com/package/markdownlint-cli

**Comment by rita3ko** [comment]
hey @jbampton !

we've just migrated our content to a new repo: https://github.com/cloudflare/cloudflare-docs (third time's the charm? 🙂). the new repo is actually going to contain all the docs for the other cloudflare products as well, but we're still in the process of migrating all the content over from some of our internal repos. 

if there's a way to reopen this, with the linting configured to be restricted to the workers content, would really appreciate you reopening it there. 

otherwise, we'll wait until we're done with the migration. 

thanks as always for your contributions! going to close this for now.

**Pull request closed without merging**
