### PR TITLE
Remove sh from shell code blocks.

### PR DESCRIPTION
**Pull request by greg-mckeon**
See #273.  This makes these code blocks copy-pasteable.

### CODE REVIEW

**Comment by ispivey** [comment]
I think you should add a `$` prompt at the beginning of each command, and leave it using the `sh` language hint: https://developers.cloudflare.com/workers/docs-engine/docs-flavored-markdown#terminals .

**Comment by greg-mckeon** [comment]
Ahh, that makes more sense, done!

**Review by ispivey — APPROVED** [review]
It looks like you're adding blank lines inside the code block. If that's unintentional, I'd suggest removing them. I don't feel strongly though 😄

**Review by adamschwartz — CHANGES_REQUESTED** [review]
Yes let’s clean up those extra lines.

**Comment by rita3ko** [comment]
@greg-mckeon — we've migrated repos, would you mind reopning your PR here https://github.com/cloudflare/cloudflare-docs/pulls? 🙏

**Pull request closed without merging**
